// Code generated by GREENPACK (github.com/glycerine/greenpack). DO NOT EDIT.

package yogadb

import (
	"fmt"

	"github.com/glycerine/greenpack/msgp"
)

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *ByteSlice) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	{
		var zgensym_9b333cce02e5f78c_0 []byte
		zgensym_9b333cce02e5f78c_0, err = dc.ReadBytes([]byte((*z)))
		(*z) = ByteSlice(zgensym_9b333cce02e5f78c_0)
	}
	if err != nil {
		return
	}
	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// EncodeMsg implements msgp.Encodable
func (z ByteSlice) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	err = en.WriteBytes([]byte(z))
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ByteSlice) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendBytes(o, []byte(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ByteSlice) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *ByteSlice) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	{
		var zgensym_9b333cce02e5f78c_1 []byte
		if nbs.AlwaysNil || msgp.IsNil(bts) {
			if !nbs.AlwaysNil {
				bts = bts[1:]
			}
			zgensym_9b333cce02e5f78c_1 = zgensym_9b333cce02e5f78c_1[:0]
		} else {
			zgensym_9b333cce02e5f78c_1, bts, err = nbs.ReadBytesBytes(bts, []byte((*z)))

			if err != nil {
				return
			}
		}
		if err != nil {
			return
		}
		(*z) = ByteSlice(zgensym_9b333cce02e5f78c_1)
	}
	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ByteSlice) Msgsize() (s int) {
	s = msgp.BytesPrefixSize + len([]byte(z))
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *GreenMEMWAL_KV) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields2zgensym_9b333cce02e5f78c_3 = 6

	// -- templateDecodeMsg starts here--
	var totalEncodedFields2zgensym_9b333cce02e5f78c_3 uint32
	totalEncodedFields2zgensym_9b333cce02e5f78c_3, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft2zgensym_9b333cce02e5f78c_3 := totalEncodedFields2zgensym_9b333cce02e5f78c_3
	missingFieldsLeft2zgensym_9b333cce02e5f78c_3 := maxFields2zgensym_9b333cce02e5f78c_3 - totalEncodedFields2zgensym_9b333cce02e5f78c_3

	var nextMiss2zgensym_9b333cce02e5f78c_3 int32 = -1
	var found2zgensym_9b333cce02e5f78c_3 [maxFields2zgensym_9b333cce02e5f78c_3]bool
	var curField2zgensym_9b333cce02e5f78c_3 string

doneWithStruct2zgensym_9b333cce02e5f78c_3:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft2zgensym_9b333cce02e5f78c_3 > 0 || missingFieldsLeft2zgensym_9b333cce02e5f78c_3 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft2zgensym_9b333cce02e5f78c_3, missingFieldsLeft2zgensym_9b333cce02e5f78c_3, msgp.ShowFound(found2zgensym_9b333cce02e5f78c_3[:]), decodeMsgFieldOrder2zgensym_9b333cce02e5f78c_3)
		if encodedFieldsLeft2zgensym_9b333cce02e5f78c_3 > 0 {
			encodedFieldsLeft2zgensym_9b333cce02e5f78c_3--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField2zgensym_9b333cce02e5f78c_3 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss2zgensym_9b333cce02e5f78c_3 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss2zgensym_9b333cce02e5f78c_3 = 0
			}
			for nextMiss2zgensym_9b333cce02e5f78c_3 < maxFields2zgensym_9b333cce02e5f78c_3 && (found2zgensym_9b333cce02e5f78c_3[nextMiss2zgensym_9b333cce02e5f78c_3] || decodeMsgFieldSkip2zgensym_9b333cce02e5f78c_3[nextMiss2zgensym_9b333cce02e5f78c_3]) {
				nextMiss2zgensym_9b333cce02e5f78c_3++
			}
			if nextMiss2zgensym_9b333cce02e5f78c_3 == maxFields2zgensym_9b333cce02e5f78c_3 {
				// filled all the empty fields!
				break doneWithStruct2zgensym_9b333cce02e5f78c_3
			}
			missingFieldsLeft2zgensym_9b333cce02e5f78c_3--
			curField2zgensym_9b333cce02e5f78c_3 = decodeMsgFieldOrder2zgensym_9b333cce02e5f78c_3[nextMiss2zgensym_9b333cce02e5f78c_3]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField2zgensym_9b333cce02e5f78c_3)
		switch curField2zgensym_9b333cce02e5f78c_3 {
		// -- templateDecodeMsg ends here --

		case "WalRecordType_zid00_i32":
			found2zgensym_9b333cce02e5f78c_3[0] = true
			z.WalRecordType, err = dc.ReadInt32()
			if err != nil {
				return
			}
		case "VptrLength_zid01_u64":
			found2zgensym_9b333cce02e5f78c_3[1] = true
			z.VptrLength, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "VptrOffset_zid02_u64":
			found2zgensym_9b333cce02e5f78c_3[2] = true
			z.VptrOffset, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "Hlc_zid03_i64":
			found2zgensym_9b333cce02e5f78c_3[3] = true
			z.Hlc, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "Key_zid04_str":
			found2zgensym_9b333cce02e5f78c_3[4] = true
			z.Key, err = dc.ReadString()
			if err != nil {
				return
			}
		case "InlineVal_zid05_bin":
			found2zgensym_9b333cce02e5f78c_3[5] = true
			z.InlineVal, err = dc.ReadBytes(z.InlineVal)
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss2zgensym_9b333cce02e5f78c_3 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of GreenMEMWAL_KV
var decodeMsgFieldOrder2zgensym_9b333cce02e5f78c_3 = []string{"WalRecordType_zid00_i32", "VptrLength_zid01_u64", "VptrOffset_zid02_u64", "Hlc_zid03_i64", "Key_zid04_str", "InlineVal_zid05_bin"}

var decodeMsgFieldSkip2zgensym_9b333cce02e5f78c_3 = []bool{false, false, false, false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *GreenMEMWAL_KV) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 6
	}
	var fieldsInUse uint32 = 6
	isempty[0] = (z.WalRecordType == 0) // number, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (z.VptrLength == 0) // number, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (z.VptrOffset == 0) // number, omitempty
	if isempty[2] {
		fieldsInUse--
	}
	isempty[3] = (z.Hlc == 0) // number, omitempty
	if isempty[3] {
		fieldsInUse--
	}
	isempty[4] = (len(z.Key) == 0) // string, omitempty
	if isempty[4] {
		fieldsInUse--
	}
	isempty[5] = (len(z.InlineVal) == 0) // string, omitempty
	if isempty[5] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *GreenMEMWAL_KV) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_9b333cce02e5f78c_4 [6]bool
	fieldsInUse_zgensym_9b333cce02e5f78c_5 := z.fieldsNotEmpty(empty_zgensym_9b333cce02e5f78c_4[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_9b333cce02e5f78c_5 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'GreenMEMWAL_KV'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x47, 0x72, 0x65, 0x65, 0x6e, 0x4d, 0x45, 0x4d, 0x57, 0x41, 0x4c, 0x5f, 0x4b, 0x56})
	if err != nil {
		return err
	}

	if !empty_zgensym_9b333cce02e5f78c_4[0] {
		// write "WalRecordType_zid00_i32"
		err = en.Append(0xb7, 0x57, 0x61, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x33, 0x32)
		if err != nil {
			return err
		}
		err = en.WriteInt32(z.WalRecordType)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_9b333cce02e5f78c_4[1] {
		// write "VptrLength_zid01_u64"
		err = en.Append(0xb4, 0x56, 0x70, 0x74, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.VptrLength)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_9b333cce02e5f78c_4[2] {
		// write "VptrOffset_zid02_u64"
		err = en.Append(0xb4, 0x56, 0x70, 0x74, 0x72, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.VptrOffset)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_9b333cce02e5f78c_4[3] {
		// write "Hlc_zid03_i64"
		err = en.Append(0xad, 0x48, 0x6c, 0x63, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.Hlc)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_9b333cce02e5f78c_4[4] {
		// write "Key_zid04_str"
		err = en.Append(0xad, 0x4b, 0x65, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Key)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_9b333cce02e5f78c_4[5] {
		// write "InlineVal_zid05_bin"
		err = en.Append(0xb3, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x61, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x62, 0x69, 0x6e)
		if err != nil {
			return err
		}
		err = en.WriteBytes(z.InlineVal)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GreenMEMWAL_KV) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [6]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "WalRecordType_zid00_i32"
		o = append(o, 0xb7, 0x57, 0x61, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x33, 0x32)
		o = msgp.AppendInt32(o, z.WalRecordType)
	}

	if !empty[1] {
		// string "VptrLength_zid01_u64"
		o = append(o, 0xb4, 0x56, 0x70, 0x74, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.VptrLength)
	}

	if !empty[2] {
		// string "VptrOffset_zid02_u64"
		o = append(o, 0xb4, 0x56, 0x70, 0x74, 0x72, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.VptrOffset)
	}

	if !empty[3] {
		// string "Hlc_zid03_i64"
		o = append(o, 0xad, 0x48, 0x6c, 0x63, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.Hlc)
	}

	if !empty[4] {
		// string "Key_zid04_str"
		o = append(o, 0xad, 0x4b, 0x65, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.Key)
	}

	if !empty[5] {
		// string "InlineVal_zid05_bin"
		o = append(o, 0xb3, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x61, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x62, 0x69, 0x6e)
		o = msgp.AppendBytes(o, z.InlineVal)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GreenMEMWAL_KV) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *GreenMEMWAL_KV) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields6zgensym_9b333cce02e5f78c_7 = 6

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields6zgensym_9b333cce02e5f78c_7 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields6zgensym_9b333cce02e5f78c_7, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft6zgensym_9b333cce02e5f78c_7 := totalEncodedFields6zgensym_9b333cce02e5f78c_7
	missingFieldsLeft6zgensym_9b333cce02e5f78c_7 := maxFields6zgensym_9b333cce02e5f78c_7 - totalEncodedFields6zgensym_9b333cce02e5f78c_7

	var nextMiss6zgensym_9b333cce02e5f78c_7 int32 = -1
	var found6zgensym_9b333cce02e5f78c_7 [maxFields6zgensym_9b333cce02e5f78c_7]bool
	var curField6zgensym_9b333cce02e5f78c_7 string

doneWithStruct6zgensym_9b333cce02e5f78c_7:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft6zgensym_9b333cce02e5f78c_7 > 0 || missingFieldsLeft6zgensym_9b333cce02e5f78c_7 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft6zgensym_9b333cce02e5f78c_7, missingFieldsLeft6zgensym_9b333cce02e5f78c_7, msgp.ShowFound(found6zgensym_9b333cce02e5f78c_7[:]), unmarshalMsgFieldOrder6zgensym_9b333cce02e5f78c_7)
		if encodedFieldsLeft6zgensym_9b333cce02e5f78c_7 > 0 {
			encodedFieldsLeft6zgensym_9b333cce02e5f78c_7--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField6zgensym_9b333cce02e5f78c_7 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss6zgensym_9b333cce02e5f78c_7 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss6zgensym_9b333cce02e5f78c_7 = 0
			}
			for nextMiss6zgensym_9b333cce02e5f78c_7 < maxFields6zgensym_9b333cce02e5f78c_7 && (found6zgensym_9b333cce02e5f78c_7[nextMiss6zgensym_9b333cce02e5f78c_7] || unmarshalMsgFieldSkip6zgensym_9b333cce02e5f78c_7[nextMiss6zgensym_9b333cce02e5f78c_7]) {
				nextMiss6zgensym_9b333cce02e5f78c_7++
			}
			if nextMiss6zgensym_9b333cce02e5f78c_7 == maxFields6zgensym_9b333cce02e5f78c_7 {
				// filled all the empty fields!
				break doneWithStruct6zgensym_9b333cce02e5f78c_7
			}
			missingFieldsLeft6zgensym_9b333cce02e5f78c_7--
			curField6zgensym_9b333cce02e5f78c_7 = unmarshalMsgFieldOrder6zgensym_9b333cce02e5f78c_7[nextMiss6zgensym_9b333cce02e5f78c_7]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField6zgensym_9b333cce02e5f78c_7)
		switch curField6zgensym_9b333cce02e5f78c_7 {
		// -- templateUnmarshalMsg ends here --

		case "WalRecordType_zid00_i32":
			found6zgensym_9b333cce02e5f78c_7[0] = true
			z.WalRecordType, bts, err = nbs.ReadInt32Bytes(bts)

			if err != nil {
				return
			}
		case "VptrLength_zid01_u64":
			found6zgensym_9b333cce02e5f78c_7[1] = true
			z.VptrLength, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "VptrOffset_zid02_u64":
			found6zgensym_9b333cce02e5f78c_7[2] = true
			z.VptrOffset, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "Hlc_zid03_i64":
			found6zgensym_9b333cce02e5f78c_7[3] = true
			z.Hlc, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		case "Key_zid04_str":
			found6zgensym_9b333cce02e5f78c_7[4] = true
			z.Key, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "InlineVal_zid05_bin":
			found6zgensym_9b333cce02e5f78c_7[5] = true
			if nbs.AlwaysNil || msgp.IsNil(bts) {
				if !nbs.AlwaysNil {
					bts = bts[1:]
				}
				z.InlineVal = z.InlineVal[:0]
			} else {
				z.InlineVal, bts, err = nbs.ReadBytesBytes(bts, z.InlineVal)

				if err != nil {
					return
				}
			}
			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss6zgensym_9b333cce02e5f78c_7 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of GreenMEMWAL_KV
var unmarshalMsgFieldOrder6zgensym_9b333cce02e5f78c_7 = []string{"WalRecordType_zid00_i32", "VptrLength_zid01_u64", "VptrOffset_zid02_u64", "Hlc_zid03_i64", "Key_zid04_str", "InlineVal_zid05_bin"}

var unmarshalMsgFieldSkip6zgensym_9b333cce02e5f78c_7 = []bool{false, false, false, false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GreenMEMWAL_KV) Msgsize() (s int) {
	s = 1 + 24 + msgp.Int32Size + 21 + msgp.Uint64Size + 21 + msgp.Uint64Size + 14 + msgp.Int64Size + 14 + msgp.StringPrefixSize + len(z.Key) + 20 + msgp.BytesPrefixSize + len(z.InlineVal)
	return
}
func (z *GreenMEMWAL_KV) Gstring() (r string) {
	r = "&GreenMEMWAL_KV{\n"
	r += fmt.Sprintf("WalRecordType: %v,\n", z.WalRecordType)
	r += fmt.Sprintf("   VptrLength: %v,\n", z.VptrLength)
	r += fmt.Sprintf("   VptrOffset: %v,\n", z.VptrOffset)
	r += fmt.Sprintf("          Hlc: %v,\n", z.Hlc)
	r += fmt.Sprintf("          Key: \"%v\",\n", z.Key)
	r += fmt.Sprintf("    InlineVal: %v,\n", z.InlineVal)
	r += "}\n"
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *UnframeError) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	{
		var zgensym_9b333cce02e5f78c_8 int
		zgensym_9b333cce02e5f78c_8, err = dc.ReadInt()
		(*z) = UnframeError(zgensym_9b333cce02e5f78c_8)
	}
	if err != nil {
		return
	}
	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// EncodeMsg implements msgp.Encodable
func (z UnframeError) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	err = en.WriteInt(int(z))
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z UnframeError) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt(o, int(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *UnframeError) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *UnframeError) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	{
		var zgensym_9b333cce02e5f78c_9 int
		zgensym_9b333cce02e5f78c_9, bts, err = nbs.ReadIntBytes(bts)

		if err != nil {
			return
		}
		(*z) = UnframeError(zgensym_9b333cce02e5f78c_9)
	}
	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z UnframeError) Msgsize() (s int) {
	s = msgp.IntSize
	return
}
