// Code generated by GREENPACK (github.com/glycerine/greenpack). DO NOT EDIT.

package yogadb

import (
	"fmt"

	"github.com/glycerine/greenpack/msgp"
)

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *GreenMemWalKV) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields1zgensym_9b333cce02e5f78c_2 = 7

	// -- templateDecodeMsg starts here--
	var totalEncodedFields1zgensym_9b333cce02e5f78c_2 uint32
	totalEncodedFields1zgensym_9b333cce02e5f78c_2, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft1zgensym_9b333cce02e5f78c_2 := totalEncodedFields1zgensym_9b333cce02e5f78c_2
	missingFieldsLeft1zgensym_9b333cce02e5f78c_2 := maxFields1zgensym_9b333cce02e5f78c_2 - totalEncodedFields1zgensym_9b333cce02e5f78c_2

	var nextMiss1zgensym_9b333cce02e5f78c_2 int32 = -1
	var found1zgensym_9b333cce02e5f78c_2 [maxFields1zgensym_9b333cce02e5f78c_2]bool
	var curField1zgensym_9b333cce02e5f78c_2 string

doneWithStruct1zgensym_9b333cce02e5f78c_2:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft1zgensym_9b333cce02e5f78c_2 > 0 || missingFieldsLeft1zgensym_9b333cce02e5f78c_2 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft1zgensym_9b333cce02e5f78c_2, missingFieldsLeft1zgensym_9b333cce02e5f78c_2, msgp.ShowFound(found1zgensym_9b333cce02e5f78c_2[:]), decodeMsgFieldOrder1zgensym_9b333cce02e5f78c_2)
		if encodedFieldsLeft1zgensym_9b333cce02e5f78c_2 > 0 {
			encodedFieldsLeft1zgensym_9b333cce02e5f78c_2--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField1zgensym_9b333cce02e5f78c_2 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss1zgensym_9b333cce02e5f78c_2 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss1zgensym_9b333cce02e5f78c_2 = 0
			}
			for nextMiss1zgensym_9b333cce02e5f78c_2 < maxFields1zgensym_9b333cce02e5f78c_2 && (found1zgensym_9b333cce02e5f78c_2[nextMiss1zgensym_9b333cce02e5f78c_2] || decodeMsgFieldSkip1zgensym_9b333cce02e5f78c_2[nextMiss1zgensym_9b333cce02e5f78c_2]) {
				nextMiss1zgensym_9b333cce02e5f78c_2++
			}
			if nextMiss1zgensym_9b333cce02e5f78c_2 == maxFields1zgensym_9b333cce02e5f78c_2 {
				// filled all the empty fields!
				break doneWithStruct1zgensym_9b333cce02e5f78c_2
			}
			missingFieldsLeft1zgensym_9b333cce02e5f78c_2--
			curField1zgensym_9b333cce02e5f78c_2 = decodeMsgFieldOrder1zgensym_9b333cce02e5f78c_2[nextMiss1zgensym_9b333cce02e5f78c_2]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField1zgensym_9b333cce02e5f78c_2)
		switch curField1zgensym_9b333cce02e5f78c_2 {
		// -- templateDecodeMsg ends here --

		case "WalRecordType_zid00_i32":
			found1zgensym_9b333cce02e5f78c_2[0] = true
			z.WalRecordType, err = dc.ReadInt32()
			if err != nil {
				return
			}
		case "CRC32c_zid01_ary":
			found1zgensym_9b333cce02e5f78c_2[1] = true
			if dc.AlwaysNil {
				// nothing more here
			} else if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					return
				}
			}
			err = dc.ReadExactBytes(z.CRC32c[:])
			if err != nil {
				return
			}
		case "VptrLength_zid02_u64":
			found1zgensym_9b333cce02e5f78c_2[2] = true
			z.VptrLength, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "VptrOffset_zid03_u64":
			found1zgensym_9b333cce02e5f78c_2[3] = true
			z.VptrOffset, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "Hlc_zid04_i64":
			found1zgensym_9b333cce02e5f78c_2[4] = true
			z.Hlc, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "Key_zid05_str":
			found1zgensym_9b333cce02e5f78c_2[5] = true
			z.Key, err = dc.ReadString()
			if err != nil {
				return
			}
		case "InlineVal_zid06_bin":
			found1zgensym_9b333cce02e5f78c_2[6] = true
			z.InlineVal, err = dc.ReadBytes(z.InlineVal)
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss1zgensym_9b333cce02e5f78c_2 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of GreenMemWalKV
var decodeMsgFieldOrder1zgensym_9b333cce02e5f78c_2 = []string{"WalRecordType_zid00_i32", "CRC32c_zid01_ary", "VptrLength_zid02_u64", "VptrOffset_zid03_u64", "Hlc_zid04_i64", "Key_zid05_str", "InlineVal_zid06_bin"}

var decodeMsgFieldSkip1zgensym_9b333cce02e5f78c_2 = []bool{false, false, false, false, false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *GreenMemWalKV) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 7
	}
	var fieldsInUse uint32 = 7
	isempty[0] = (z.WalRecordType == 0) // number, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (len(z.CRC32c) == 0) // string, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (z.VptrLength == 0) // number, omitempty
	if isempty[2] {
		fieldsInUse--
	}
	isempty[3] = (z.VptrOffset == 0) // number, omitempty
	if isempty[3] {
		fieldsInUse--
	}
	isempty[4] = (z.Hlc == 0) // number, omitempty
	if isempty[4] {
		fieldsInUse--
	}
	isempty[5] = (len(z.Key) == 0) // string, omitempty
	if isempty[5] {
		fieldsInUse--
	}
	isempty[6] = (len(z.InlineVal) == 0) // string, omitempty
	if isempty[6] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *GreenMemWalKV) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_9b333cce02e5f78c_3 [7]bool
	fieldsInUse_zgensym_9b333cce02e5f78c_4 := z.fieldsNotEmpty(empty_zgensym_9b333cce02e5f78c_3[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_9b333cce02e5f78c_4 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'GreenMemWalKV'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x47, 0x72, 0x65, 0x65, 0x6e, 0x4d, 0x65, 0x6d, 0x57, 0x61, 0x6c, 0x4b, 0x56})
	if err != nil {
		return err
	}

	if !empty_zgensym_9b333cce02e5f78c_3[0] {
		// write "WalRecordType_zid00_i32"
		err = en.Append(0xb7, 0x57, 0x61, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x33, 0x32)
		if err != nil {
			return err
		}
		err = en.WriteInt32(z.WalRecordType)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_9b333cce02e5f78c_3[1] {
		// write "CRC32c_zid01_ary"
		err = en.Append(0xb0, 0x43, 0x52, 0x43, 0x33, 0x32, 0x63, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x61, 0x72, 0x79)
		if err != nil {
			return err
		}
		err = en.WriteBytes(z.CRC32c[:])
		if err != nil {
			return
		}
	}

	if !empty_zgensym_9b333cce02e5f78c_3[2] {
		// write "VptrLength_zid02_u64"
		err = en.Append(0xb4, 0x56, 0x70, 0x74, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.VptrLength)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_9b333cce02e5f78c_3[3] {
		// write "VptrOffset_zid03_u64"
		err = en.Append(0xb4, 0x56, 0x70, 0x74, 0x72, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.VptrOffset)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_9b333cce02e5f78c_3[4] {
		// write "Hlc_zid04_i64"
		err = en.Append(0xad, 0x48, 0x6c, 0x63, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.Hlc)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_9b333cce02e5f78c_3[5] {
		// write "Key_zid05_str"
		err = en.Append(0xad, 0x4b, 0x65, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Key)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_9b333cce02e5f78c_3[6] {
		// write "InlineVal_zid06_bin"
		err = en.Append(0xb3, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x61, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x36, 0x5f, 0x62, 0x69, 0x6e)
		if err != nil {
			return err
		}
		err = en.WriteBytes(z.InlineVal)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GreenMemWalKV) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [7]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "WalRecordType_zid00_i32"
		o = append(o, 0xb7, 0x57, 0x61, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x33, 0x32)
		o = msgp.AppendInt32(o, z.WalRecordType)
	}

	if !empty[1] {
		// string "CRC32c_zid01_ary"
		o = append(o, 0xb0, 0x43, 0x52, 0x43, 0x33, 0x32, 0x63, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x61, 0x72, 0x79)
		o = msgp.AppendBytes(o, z.CRC32c[:])
	}

	if !empty[2] {
		// string "VptrLength_zid02_u64"
		o = append(o, 0xb4, 0x56, 0x70, 0x74, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.VptrLength)
	}

	if !empty[3] {
		// string "VptrOffset_zid03_u64"
		o = append(o, 0xb4, 0x56, 0x70, 0x74, 0x72, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.VptrOffset)
	}

	if !empty[4] {
		// string "Hlc_zid04_i64"
		o = append(o, 0xad, 0x48, 0x6c, 0x63, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.Hlc)
	}

	if !empty[5] {
		// string "Key_zid05_str"
		o = append(o, 0xad, 0x4b, 0x65, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.Key)
	}

	if !empty[6] {
		// string "InlineVal_zid06_bin"
		o = append(o, 0xb3, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x61, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x36, 0x5f, 0x62, 0x69, 0x6e)
		o = msgp.AppendBytes(o, z.InlineVal)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GreenMemWalKV) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *GreenMemWalKV) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields5zgensym_9b333cce02e5f78c_6 = 7

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields5zgensym_9b333cce02e5f78c_6 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields5zgensym_9b333cce02e5f78c_6, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft5zgensym_9b333cce02e5f78c_6 := totalEncodedFields5zgensym_9b333cce02e5f78c_6
	missingFieldsLeft5zgensym_9b333cce02e5f78c_6 := maxFields5zgensym_9b333cce02e5f78c_6 - totalEncodedFields5zgensym_9b333cce02e5f78c_6

	var nextMiss5zgensym_9b333cce02e5f78c_6 int32 = -1
	var found5zgensym_9b333cce02e5f78c_6 [maxFields5zgensym_9b333cce02e5f78c_6]bool
	var curField5zgensym_9b333cce02e5f78c_6 string

doneWithStruct5zgensym_9b333cce02e5f78c_6:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft5zgensym_9b333cce02e5f78c_6 > 0 || missingFieldsLeft5zgensym_9b333cce02e5f78c_6 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft5zgensym_9b333cce02e5f78c_6, missingFieldsLeft5zgensym_9b333cce02e5f78c_6, msgp.ShowFound(found5zgensym_9b333cce02e5f78c_6[:]), unmarshalMsgFieldOrder5zgensym_9b333cce02e5f78c_6)
		if encodedFieldsLeft5zgensym_9b333cce02e5f78c_6 > 0 {
			encodedFieldsLeft5zgensym_9b333cce02e5f78c_6--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField5zgensym_9b333cce02e5f78c_6 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss5zgensym_9b333cce02e5f78c_6 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss5zgensym_9b333cce02e5f78c_6 = 0
			}
			for nextMiss5zgensym_9b333cce02e5f78c_6 < maxFields5zgensym_9b333cce02e5f78c_6 && (found5zgensym_9b333cce02e5f78c_6[nextMiss5zgensym_9b333cce02e5f78c_6] || unmarshalMsgFieldSkip5zgensym_9b333cce02e5f78c_6[nextMiss5zgensym_9b333cce02e5f78c_6]) {
				nextMiss5zgensym_9b333cce02e5f78c_6++
			}
			if nextMiss5zgensym_9b333cce02e5f78c_6 == maxFields5zgensym_9b333cce02e5f78c_6 {
				// filled all the empty fields!
				break doneWithStruct5zgensym_9b333cce02e5f78c_6
			}
			missingFieldsLeft5zgensym_9b333cce02e5f78c_6--
			curField5zgensym_9b333cce02e5f78c_6 = unmarshalMsgFieldOrder5zgensym_9b333cce02e5f78c_6[nextMiss5zgensym_9b333cce02e5f78c_6]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField5zgensym_9b333cce02e5f78c_6)
		switch curField5zgensym_9b333cce02e5f78c_6 {
		// -- templateUnmarshalMsg ends here --

		case "WalRecordType_zid00_i32":
			found5zgensym_9b333cce02e5f78c_6[0] = true
			z.WalRecordType, bts, err = nbs.ReadInt32Bytes(bts)

			if err != nil {
				return
			}
		case "CRC32c_zid01_ary":
			found5zgensym_9b333cce02e5f78c_6[1] = true
			bts, err = nbs.ReadExactBytes(bts, z.CRC32c[:])
			if err != nil {
				return
			}
		case "VptrLength_zid02_u64":
			found5zgensym_9b333cce02e5f78c_6[2] = true
			z.VptrLength, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "VptrOffset_zid03_u64":
			found5zgensym_9b333cce02e5f78c_6[3] = true
			z.VptrOffset, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "Hlc_zid04_i64":
			found5zgensym_9b333cce02e5f78c_6[4] = true
			z.Hlc, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		case "Key_zid05_str":
			found5zgensym_9b333cce02e5f78c_6[5] = true
			z.Key, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "InlineVal_zid06_bin":
			found5zgensym_9b333cce02e5f78c_6[6] = true
			if nbs.AlwaysNil || msgp.IsNil(bts) {
				if !nbs.AlwaysNil {
					bts = bts[1:]
				}
				z.InlineVal = z.InlineVal[:0]
			} else {
				z.InlineVal, bts, err = nbs.ReadBytesBytes(bts, z.InlineVal)

				if err != nil {
					return
				}
			}
			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss5zgensym_9b333cce02e5f78c_6 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of GreenMemWalKV
var unmarshalMsgFieldOrder5zgensym_9b333cce02e5f78c_6 = []string{"WalRecordType_zid00_i32", "CRC32c_zid01_ary", "VptrLength_zid02_u64", "VptrOffset_zid03_u64", "Hlc_zid04_i64", "Key_zid05_str", "InlineVal_zid06_bin"}

var unmarshalMsgFieldSkip5zgensym_9b333cce02e5f78c_6 = []bool{false, false, false, false, false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GreenMemWalKV) Msgsize() (s int) {
	s = 1 + 24 + msgp.Int32Size + 17 + msgp.ArrayHeaderSize + (4 * (msgp.ByteSize)) + 21 + msgp.Uint64Size + 21 + msgp.Uint64Size + 14 + msgp.Int64Size + 14 + msgp.StringPrefixSize + len(z.Key) + 20 + msgp.BytesPrefixSize + len(z.InlineVal)
	return
}
func (z *GreenMemWalKV) Gstring() (r string) {
	r = "&GreenMemWalKV{\n"
	r += fmt.Sprintf("WalRecordType: %v,\n", z.WalRecordType)
	r += fmt.Sprintf("       CRC32c: %v,\n", z.CRC32c)
	r += fmt.Sprintf("   VptrLength: %v,\n", z.VptrLength)
	r += fmt.Sprintf("   VptrOffset: %v,\n", z.VptrOffset)
	r += fmt.Sprintf("          Hlc: %v,\n", z.Hlc)
	r += fmt.Sprintf("          Key: \"%v\",\n", z.Key)
	r += fmt.Sprintf("    InlineVal: %v,\n", z.InlineVal)
	r += "}\n"
	return
}
